### ISSUE TITLE
[Suggestion] Config file option

### ISSUE THREAD

**Issue by xenornithos** [Matyrobbrt/better-mob-griefing-control#2]
Could there be an option to configure the griefing game rules in a TOML file, please? I find it easier to enable or disable features using these over individual commands (especially in modpacks where I mostly edit configs in-game or directly in the TOML files).

**Comment by KiriCattus** [comment]
The mod was intended more for server/single player usage rather than presetting values in a pack but I can at least attempt to sort that out later but no promises since I'm not sure how well the game will take to game rules being set by config

**Comment by xenornithos** [comment]
Okay, however it works out.

**Comment by KiriCattus** [comment]
Meant to ask earlier what version are you after?

**Comment by xenornithos** [comment]
1.19.2.

**Comment by KiriCattus** [comment]
Special build that should work across 1.19 in general released, though if the config overrides are enabled the in game commands will do nothing but exist. https://www.curseforge.com/minecraft/mc-mods/better-mob-griefing-control/files/4370092

**Comment by xenornithos** [comment]
It works great -- thanks for making this build!
